### PR TITLE
badr

### PR DESCRIPTION
**Pull request by BadrAljohani**

### CODE REVIEW

**Comment by azfay3** [comment]
Badr, you have crash when try to return blue cell to Main Collection View `Fatal error: Index out of range`, please ensure both of Red and Blue cells can return to Main Collection View.

**Comment by azfay3** [comment]
Commit and push once you solved above crash.

**Comment by BadrAljohani** [comment]
The requested modification has been made and Animations have been added for all cells

**Comment by BadrAljohani** [comment]
The requested modification has been made and Animations have been added for all cells

**Comment by azfay3** [comment]
Adoption of animation on 2D graphics is bonus, Great job!

**Pull request closed without merging**
